"""
Renders a single camp-visit (registration) into a PDF report.

Uses reportlab (pip install reportlab) — pure Python, no system-level
dependencies like wkhtmltopdf/WeasyPrint need, so it drops into any
deployment without extra setup.

Colors match the Vitera logo: navy #0B3D78, green #1F6D35.
"""

import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from .patients_schema import PatientFullDetail, RegistrationDetail

NAVY = colors.HexColor("#0B3D78")
GREEN = colors.HexColor("#1F6D35")
LIGHT_GREEN = colors.HexColor("#EEF6EA")
BORDER = colors.HexColor("#DCE6DD")

# Optional: if you drop a logo file at this path, it's included in the
# header. Safe to leave absent — the report just skips it.
LOGO_PATH = os.path.join(os.path.dirname(__file__), "..", "static", "vitera-logo.png")

_styles = getSampleStyleSheet()
_TITLE = ParagraphStyle("VTitle", parent=_styles["Title"], textColor=NAVY, fontSize=18, spaceAfter=2)
_SUBTITLE = ParagraphStyle("VSubtitle", parent=_styles["Normal"], textColor=colors.grey, fontSize=9)
_SECTION = ParagraphStyle(
    "VSection", parent=_styles["Heading2"], textColor=NAVY, fontSize=12, spaceBefore=14, spaceAfter=6
)
_BODY = ParagraphStyle("VBody", parent=_styles["Normal"], fontSize=9.5, leading=13)
_LABEL = ParagraphStyle("VLabel", parent=_styles["Normal"], fontSize=8, textColor=colors.grey)


def _kv_table(pairs: list[tuple[str, str]], col_widths=None) -> Table:
    """Two-column label/value grid, styled like a set of stat chips."""
    rows = []
    row = []
    for label, value in pairs:
        row.append(Paragraph(f"<b>{label}</b><br/>{value or '—'}", _BODY))
        if len(row) == 2:
            rows.append(row)
            row = []
    if row:
        row.append("")
        rows.append(row)

    table = Table(rows, colWidths=col_widths or [90 * mm, 90 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GREEN),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def _checklist_line(history) -> str:
    flags = [
        ("Diabetes", history.has_diabetes),
        ("Hypertension", history.has_hypertension),
        ("TB", history.has_tb),
        ("Asthma/COPD", history.has_asthma_copd),
        ("Cardiac disease", history.has_cardiac_disease),
        ("Renal disease", history.has_renal_disease),
        ("Liver disease", history.has_liver_disease),
    ]
    present = [name for name, flag in flags if flag]
    return ", ".join(present) if present else "None reported"


def build_registration_pdf(patient: PatientFullDetail, reg: RegistrationDetail) -> bytes:
    import io

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        title=f"Vitera Camp Report — {reg.registration_code}",
    )

    story = []

    # ---------- Header ----------
    if os.path.exists(LOGO_PATH):
        header = Table(
            [[Image(LOGO_PATH, width=28 * mm, height=28 * mm), Paragraph("Camp Visit Report", _TITLE)]],
            colWidths=[32 * mm, None],
        )
        header.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
        story.append(header)
    else:
        story.append(Paragraph("VITERA — Camp Visit Report", _TITLE))

    story.append(Paragraph(f"{reg.registration_code} · Generated by Vitera Health", _SUBTITLE))
    story.append(Spacer(1, 10))

    # ---------- Patient info ----------
    story.append(Paragraph("Patient", _SECTION))
    story.append(
        _kv_table(
            [
                ("Name", patient.name),
                ("Patient Code", patient.patient_code),
                ("Phone", patient.phone),
                ("Email", patient.email),
                ("Gender", patient.gender.value if patient.gender else None),
                ("DOB / Age", patient.dob_or_age),
                ("Family Code", patient.family_code),
                ("Address", patient.address),
            ]
        )
    )

    # ---------- Visit info ----------
    story.append(Paragraph("Camp Visit", _SECTION))
    story.append(
        _kv_table(
            [
                ("Camp", f"{reg.camp_code or '—'} ({reg.camp_date or '—'})"),
                ("Slot", reg.slot_label),
                ("Building", reg.building_name),
                ("Status", reg.status.value.replace("_", " ").title()),
                ("Service Interest", reg.service_interest),
                ("Registered At", reg.registered_at.strftime("%d %b %Y, %I:%M %p")),
                (
                    "Checked In At",
                    reg.checked_in_at.strftime("%d %b %Y, %I:%M %p") if reg.checked_in_at else None,
                ),
                (
                    "Completed At",
                    reg.completed_at.strftime("%d %b %Y, %I:%M %p") if reg.completed_at else None,
                ),
            ]
        )
    )

    # ---------- Vitals ----------
    story.append(Paragraph("Vitals", _SECTION))
    v = reg.vitals
    if v:
        story.append(
            _kv_table(
                [
                    ("Height / Weight", f"{v.height_cm or '—'} cm / {v.weight_kg or '—'} kg"),
                    ("BMI", v.bmi),
                    ("Blood Pressure", f"{v.systolic_bp or '—'}/{v.diastolic_bp or '—'} mmHg"),
                    (
                        "Blood Sugar",
                        f"{v.blood_sugar or '—'} ({v.blood_sugar_type.value if v.blood_sugar_type else '—'})",
                    ),
                    ("Temperature", f"{v.temperature_celsius or '—'} °C"),
                    (
                        "Bone Density",
                        f"{v.bone_density_bmd or '—'} (T:{v.bone_density_t_score or '—'} Z:{v.bone_density_z_score or '—'}, {v.bone_density_site or '—'})",
                    ),
                ]
            )
        )
    else:
        story.append(Paragraph("No vitals recorded for this visit.", _BODY))

    # ---------- Medical history ----------
    story.append(Paragraph("Medical History", _SECTION))
    h = reg.medical_history
    if h:
        if h.chief_complaint:
            story.append(Paragraph(f"<b>Chief complaint:</b> {h.chief_complaint}", _BODY))
            story.append(Spacer(1, 4))
        story.append(Paragraph(f"<b>Known conditions:</b> {_checklist_line(h)}", _BODY))
        for label, value in [
            ("Other major illnesses", h.other_major_illnesses),
            ("Existing conditions", h.existing_conditions),
            ("Current medications", h.current_medications),
            ("Allergies", h.allergies),
            ("Past surgeries", h.past_surgeries),
            ("Family history", h.family_history),
            ("Lifestyle notes", h.lifestyle_notes),
        ]:
            if value:
                story.append(Spacer(1, 4))
                story.append(Paragraph(f"<b>{label}:</b> {value}", _BODY))
    else:
        story.append(Paragraph("No medical history recorded for this visit.", _BODY))

    # ---------- Consultation ----------
    story.append(Paragraph("Consultation", _SECTION))
    c = reg.consultation
    if c:
        story.append(Paragraph(f"<b>Doctor:</b> {c.doctor_name}", _BODY))
        for label, value in [
            ("Clinical observations", c.clinical_observations),
            ("Diagnosis", c.diagnosis),
            ("Doctor notes", c.doctor_notes),
            ("Recommendations", c.recommendations),
        ]:
            if value:
                story.append(Spacer(1, 4))
                story.append(Paragraph(f"<b>{label}:</b> {value}", _BODY))

        story.append(Spacer(1, 8))
        if c.prescriptions:
            rx_rows = [["Medicine", "Dosage", "Frequency", "Duration", "Instructions"]]
            for p in c.prescriptions:
                rx_rows.append(
                    [
                        p.medicine_name,
                        p.dosage or "—",
                        p.frequency or "—",
                        p.duration or "—",
                        p.instructions or "—",
                    ]
                )
            rx_table = Table(rx_rows, colWidths=[35 * mm, 25 * mm, 30 * mm, 25 * mm, 63 * mm])
            rx_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 5),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREEN]),
                    ]
                )
            )
            story.append(rx_table)
        else:
            story.append(Paragraph("No medicines prescribed.", _BODY))
    else:
        story.append(Paragraph("No consultation recorded for this visit.", _BODY))

    doc.build(story)
    return buffer.getvalue()